version: '3.8'

services:
  pokemon-api-proxy:
    build: .
    container_name: pokemon-api-proxy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POKEMON_API_BASE_URL=https://pokeapi.co/api/v2
      - POKEMON_API_TIMEOUT=5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - pokemon-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    networks:
      - pokemon-network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=n8n
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    restart: unless-stopped
    networks:
      - pokemon-network

networks:
  pokemon-network:
    driver: bridge

volumes:
  jenkins_home:
  n8n_data:
